# Generated by Django 5.2.1 on 2025-06-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
