# Generated by Django 5.2.1 on 2025-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='senddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
