# Generated by Django 5.2.1 on 2025-05-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_certificate_senddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='startdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.enrollment'),
        ),
    ]
