# Generated by Django 5.2.1 on 2025-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_enrollment_alter_certificate_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='startdate',
            field=models.DateField(),
        ),
    ]
