# Generated by Django 5.2.1 on 2025-06-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
    ]
