# Generated by Django 5.2.1 on 2025-05-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_certificate_startdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
