# Generated by Django 5.2.1 on 2025-06-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_course_duration_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enroll_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
