# Generated by Django 5.2.1 on 2025-05-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
