# Generated by Django 5.2.1 on 2025-05-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_enrollment_enroll_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
