# Generated by Django 5.2.1 on 2025-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_enrollment_enroll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
