# Generated by Django 5.2.1 on 2025-06-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_enrollment_enroll_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
