# Generated by Django 5.2.1 on 2025-06-01 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
