# Generated by Django 5.2.1 on 2025-06-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_course_start_date_enrollment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.trainer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.course'),
        ),
    ]
