# Generated by Django 5.2.1 on 2025-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_trainer_course_trainer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
