# Generated by Django 5.2.1 on 2025-07-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_course_trainer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
